### ISSUE TITLE
Change Button Layout

### ISSUE THREAD

**Issue by Kazanagi** [mariuste/SlimBoxPCB#3]
Change button positions to the following tables. The positions in the table are relative to the bottom left hole of the PCB.

|Button|x-position|y-position|
|---|---:|---:|
|S2|15.00|95.00|
|S1|33.90|95.00|
|Home|52.80|95.00|
|Left|29.50|68.00|
|Down|48.50|68.00|
|Right|67.50|63.00|
|Up|73.00|10.65|
|A2|9.50|45.50|
|L3|98.50|52.50|
|R3|121.50|10.65|
|B1|123.50|42.81|
|B2|148.50|52.04|
|B3|119.50|68.50|
|B4|145.50|77.87|
|L1|173.00|78.00|
|L2|174.50|52.04|
|R1|199.50|64.50|
|R2|199.50|38.50|

Additonally remove the upper middle hole and add two holes beside the MC. See attached zip for details.

A new siwtch A2 should be added and wired to GPIO15 (https://gp2040-ce.info/controller-build/wiring/#waveshare-rp2040-zero)

[wasd_plate v17.zip](https://github.com/mariuste/SlimBoxPCB/files/13692331/wasd_plate.v17.zip)

**Comment by mariuste** [comment]
done
